In [175]:
import torch
import numpy as np

In [176]:
mat=np.arange(9)
t=torch.tensor(mat)

t, t.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

1.

In [177]:
t1=torch.reshape(t,(3,3))
t1, t1.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 torch.Size([3, 3]))

In [178]:
t1=t.view((3,3))
t1, t1.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 torch.Size([3, 3]))

In [179]:
t1=torch.stack((t1,t1))
t1,t1.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
         [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 torch.Size([2, 9]))

In [180]:
t1=torch.squeeze(t1)
t1,t1.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
         [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 torch.Size([2, 9]))

In [181]:
t1=torch.unsqueeze(t1,dim=1)
t1,t1.shape

(tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8]],
 
         [[0, 1, 2, 3, 4, 5, 6, 7, 8]]]),
 torch.Size([2, 1, 9]))

2.

In [182]:
t2=torch.permute(t1,dims=(2,0,3,1))
t2,t2.shape

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 4

3.

In [140]:
t1[1:]

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [141]:
t1[1:,0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [142]:
t1[1:,0,:2]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [143]:
t1[1:,0,:2,:]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

4.

In [144]:
arr=np.array(mat)
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [145]:
t3=torch.from_numpy(arr)
t3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [146]:
arr=t3.numpy()
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

5.

In [147]:
t4=torch.rand((7,7))
t4.shape

torch.Size([7, 7])

6.

In [148]:
t5=torch.rand((1,7))
t5.shape

torch.Size([1, 7])

In [149]:
t6=torch.matmul(t4,t5.transpose(0,1))
t6.shape

torch.Size([7, 1])

7.

In [150]:
t7=torch.randint(0,10,(2,3))
t8=torch.randint(0,10,(2,3))

t7.device,t8.device

(device(type='cpu'), device(type='cpu'))

In [ ]:
t7=t7.to("cuda").float()
t8=t8.to("cuda").float()

t7.device,t8.device

(device(type='cuda', index=0), device(type='cuda', index=0))

8.

In [152]:
t9=t7@t8.T
t9

tensor([[62., 63.],
        [28., 35.]], device='cuda:0')

9.

In [153]:
tmax=torch.max(t9)
tmin=torch.min(t9)

print(f"Max = {tmax.item()}\nMin = {tmin.item()}")

Max = 63.0
Min = 28.0


10.

In [154]:
tmax=torch.argmax(t9)
tmin=torch.argmin(t9)

print(f"Max = {tmax.item()}\nMin = {tmin.item()}")

Max = 1
Min = 2


11.

In [155]:
torch.manual_seed(7)
t10=torch.rand((1,1,1,10))
t10, t10.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [156]:
t10=torch.squeeze(t10)
t10, t10.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))